### ISSUE TITLE
Filtering operations by tags

### ISSUE THREAD

**Issue by hlobit** [kiwicom/schemathesis#134]
OpenAPI specification allow adding tags to operations.

```yaml
tags:
- pet
summary: Updates a pet in the store with form data
operationId: updatePetWithForm
parameters:
- name: petId
  in: path
  description: ID of pet that needs to be updated
  required: true
  schema:
    type: string
...
```

It would be great to filter on these tags to get a subset of cases.
Something like:

```python
@schema.parametrize(tags=['pet'])                                                 
def test_no_server_errors(case):
    # do something with the case
    pass
```
