### ISSUE TITLE
Check alternative base paths

### ISSUE THREAD

**Issue by Stranger6667** [kiwicom/schemathesis#40]
In OAS 3 it could be specified per server:

```
servers:
  - url: http://localhost:8080/{basePath}
    description: application
    variables:
      basePath:
        default: api
```

Currently, Schemathesis only uses `basePath` from the schema root, which could not work on some OAS schemas

If we will automate this, then it will reduce the number of actions needed to run the tests, currently, the base URL should be set manually in a test case
