### ISSUE TITLE
phases=[Phase.explicit] does not consistently use examples request body

### ISSUE THREAD

**Issue by charliehohenstein30** [kiwicom/schemathesis#424]
I'm currently trying to use only explicit examples in my openApi spec file.  However, phases=[Phase.explicit] does not always use all of the example values that are declared in the RequestBody.  This should be related to https://github.com/kiwicom/schemathesis/issues/381

Here is how I am running my test:

```
# start pytest
@schema.parametrize()
@settings(max_examples=1, phases=[Phase.explicit], deadline=20000)
def test_all_endpoints(case):

    # Checking if Schema matches response
    case.validate_response(response)
```

Here is an example of the request object Im using:
```
type: object
      properties:
        _settings:
            type: array
            items:
              type: object
              properties:
                type:
                  type: string
                name:
                  type: string
                category:
                  type: string
                value:
                  type: boolean
                org_unit_id:
                  type: string
        _org_unit_id:
          type: integer
      example:
        _settings: [{"type": "org_unit_settings","name": "therapeutic_alternatives_org_unit_id","category": "data_filtering","value": "1","org_unit_id": "1"}]
        _org_unit_id: 477

```

**An example of what happens is that it will run one time correctly and has a request body:**

REQUEST BODY: {'_settings': [{'type': 'org_unit_settings', 'name': 'therapeutic_alternatives_org_unit_id', 'category': 'data_filtering', 'value': 1, 'org_unit_id': 1}], '_org_unit_id': 477}

**And then will run another time and the request body will be incorrect as this**

REQUEST BODY: {'_org_unit_id': 0}
