### ISSUE TITLE
Generating requests from examples

### ISSUE THREAD

**Issue by barrett-schonefeld** [kiwicom/schemathesis#454]
Hey, folks!

To handle cases where an API needs a specific value, such as an account id, we want to generate requests from OpenAPI examples. 

I see that Schemathesis supports generating requests from examples. Is there a way, when an example is provided in the OpenAPI description, to only use the example schema (and not use randomly generated requests)?

**Comment by Stranger6667** [comment]
Hi @barrett-schonefeld !

Yes, it is possible via `--hypothesis_phases=explicit` CLI option. I'll update the documentation to reflect this case.

**Comment by Stranger6667** [comment]
Let me know if it will work for you

**Comment by Stranger6667** [comment]
Or, if you use it in your code, then having this decorator will make the trick

```
from hypothesis import settings, Phase

...
@schema.parametrize()
@settings(phases=[Phase.explicit])
def test_api(case):
    ...
```

**Comment by barrett-schonefeld** [comment]
Yes, worked great! Just in case someone stumbles across this issue for the same reason, the command is `--hypothesis-phases=explicit` not `--hypothesis_phases=explicit`.

I think this is a great project, and I appreciate your engagement! After researching several endpoint validators, I think Schemathesis is the winner.

**Comment by Stranger6667** [comment]
I am very very happy to hear that :) let me know if I can do something to improve your experience with the project :)

P.S. I edited the message with a typo in command, thanks

**Comment by stepanbokoc** [comment]
Hi,
sorry to comment in closed issue, but I also want to generate case from example data but I think it does not work with OAS3

This data are collected during runtime. 
Here is `case.endpoint.body.properties`
```
{'name': {'type': 'string', 'example': 'D785'}, 'verify_mac': {'type': 'boolean', 'example': True}, 'mac_ranges': {'type': 'array', 'items': {'type': 'object'}, 'example': [{'start': '000413230000', 'end': '00041323ffff'}]}, 'default_settings': {'type': 'object'}, 'groups': {'type': 'array', 'items': {'type': 'string', 'format': 'uuid'}}}
```
and here is `case.body` generated from it (examples are ignored)
```
{'default_settings': {}, 'groups': [], 'mac_ranges': [], 'name': '', 'verify_mac': False}
```
I think the problem is that OAS2 used `parameters` to define body example but in OAS3 uses `schema`

**Comment by barrett-schonefeld** [comment]
I am new to the project, so I could be wrong about this, but I believe the `case` object is only the minimum representation of a valid schema.

Schemathesis generates many request objects each with different data, but `case` object acts as the simplest form of a valid schema that can be used to validate response objects.

May be better ways to do this, but using the Schemathesis hooks, you can access see the actual data sent to the API with:

    @schemathesis.register_check
    def my_hook(response, case):
        actual_request = response.request

**Comment by Stranger6667** [comment]
Hi @stepanbokoc ,
No problem, it is good that you are bringing it up here :) Could you share the original schema that you are using? The one in `case.endpoint` is computed from all parameters defined in OAS - they are combined in a single JSON Schema. Operation definition will be enough.

**Comment by stepanbokoc** [comment]
Sending minimal valid document
```
openapi: "3.0.3"
info:
  description: desc
  title: title
  version: "1.0"
servers:
  - url: http://localhost:5000

paths:
  /products/{product_code}:
    parameters:
      - name: product_code
        in: path
        required: true
        schema:
          type: string
          example: code

    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        201:
          description: d
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

components:
  securitySchemes:
    hawk:
      type: http
      scheme: bearer
      bearerFormat: HAWK
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example:
            name
        verify_mac:
          type: boolean
          example:
            True
        mac_ranges:
          type: array
          items:
            type: object
          example:
            [
              {"start": "000413230000", "end": "00041323ffff"}
            ]
        default_settings:
          type: object
        groups:
          type: array
          items:
            type: string
            format: uuid
      required:
        - name
        - default_settings
        - groups
        - mac_ranges
        - verify_mac


security:
  - hawk: []
```
And the test
```
@schema.parametrize()
@settings(phases=[Phase.explicit])
def test_exact_example(case)
    response = case.call()
```

**Comment by Stranger6667** [comment]
This case is slightly more complex and wasn't supported intentionally (I removed the comment about it from the readme without proper checking).
At the moment we support only examples that are:
- specified on a [schema level](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#fixed-fields-20) (for parameters & `requestBody`)
- on a parameter / `requestBody` level ([details](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#parameter-object))
The schema you provided contains examples on individual properties level, which is more complicated to gather in a generic case because it involves schema traversing, which may contain different item types, schemas that refer to each other, etc. I'd be happy to have support for this in the future, though and created an issue for it (#467).
E.g. in your schema, there might be examples in `Product/mac_ranges/items` (or deeper in that object as well), which is not trivial to combine (there might be multiple different examples specified on different levels, which all should be tested)

As a workaround, I can propose to add an example to the `Product` schema:

```
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example:
            name
        verify_mac:
          type: boolean
          example:
            True
        mac_ranges:
          type: array
          items:
            type: object
          example:
            [
              {"start": "000413230000", "end": "00041323ffff"}
            ]
        default_settings:
          type: object
        groups:
          type: array
          items:
            type: string
            format: uuid
      required:
        - name
        - default_settings
        - groups
        - mac_ranges
        - verify_mac
      example:
        name: name
        verify_mac: true
        mac_ranges: [{"start": "000413230000", "end": "00041323ffff"}]
```

Hope, that it clarifies the situation
