### ISSUE TITLE
Add support for querystring-based API token auth

### ISSUE THREAD

**Issue by jonahbenton** [kiwicom/schemathesis#540]
We have a swagger schema with a securityDefinitions like so:

```
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "query"
```

I don't see a way to wire an api key into the request generation process?
